export const CategoriaAtividade = [
    'Indústria',
    'Comércio',
    'Serviços',
    'Pessoa Física',
]

export const RamoAtividade = {
    'Indústria': [
        'Alimentos',
        'Automotiva',
        'Bebidas',
        'Construção Civil',
        'Cosméticos',
        'Educação',
        'Eletrônicos',
        'Energia',
        'Entretenimento',
        'Farmacêutica',
        'Financeiro',
        'Informática',
        'Logística',
        'Mecânica',
        'Metalúrgica',
        'Móveis',
        'Química',
        'Saúde',
        'Têxtil',
    ],
    'Comércio': [
        'Alimentos',
        'Automotiva',
        'Bebidas',
        'Construção Civil',
        'Cosméticos',
        'Educação',
        'Eletrônicos',
        'Energia',
        'Entretenimento',
        'Farmacêutica',
        'Financeiro',
        'Informática',
        'Logística',
        'Mecânica',
        'Metalúrgica',
        'Móveis',
        'Química',
        'Saúde',
        'Têxtil',
    ],
    'Serviços': [
        'Assessoria',
        'Consultoria',
        'Educação',
        'Informática',
        'Jurídico',
        'Marketing',
        'Saúde',
        'Segurança',
        'Transporte',
    ],
}

export const SubCategoriasServico = {
    Marketing: [
        'Agência',
        'Assessoria de Imprensa',
        'Consultoria',
        'Design Gráfico',
        'Eventos',
        'Marketing Digital',
        'Pesquisa de Mercado',
        'Produtora',
        'Publicidade',
        'Relações Públicas',
        'Telemarketing',
    ]
}